server:
  port: 9001
  context-path: /hlbb
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-wait: -1
      max-active: 8
      max-idle: 8
      min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hlbb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.exmail.qq.com
    username: tech@hilibaba.com
    password: Zhou1990rui
    properties:
      mail:
        smtp:
          auth: true
appId: 09931
      